# Rime default settings
# encoding: utf-8

config_version: "0.27"

schema_list:
    - schema: bopomofo             # 注音（正體模式）
    - schema: bopomofo_chs         # 注音（簡體模式）
#   - schema: emoji  　　　　       # emoji表情
#   - schema: luna_pinyin          # 朙月拼音
#   - schema: luna_pinyin_simp     # 朙月拼音 简化字模式
#   - schema: luna_pinyin_tw       # 朙月拼音 臺灣正體模式
#   - schema: terra_pinyin         # 地球拼音 dì qi
#   - schema: jyutping             # 粵拼
#   - schema: cangjie5             # 倉頡五代
#   - schema: cangjie5_express     # 倉頡 快打模式
#   - schema: quick5               # 速成
#   - schema: wubi86               # 五笔86
#   - schema: wubi_pinyin          # 五笔拼音混合輸入
#   - schema: double_pinyin        # 自然碼雙拼
#   - schema: double_pinyin_mspy   # 微軟雙拼
#   - schema: double_pinyin_abc    # 智能ABC雙拼
#   - schema: double_pinyin_flypy  # 小鶴雙拼
#   - schema: wugniu               # 吳語上海話（新派）
#   - schema: wugniu_lopha         # 吳語上海話（老派）
#   - schema: triungkox3p          # 中古漢語三拼
#   - schema: zyenpheng            # 中古漢語全拼
#   - schema: ipa_xsampa           # X-SAMPA 國際音標

switcher:
  caption: 〔輸入法切換〕
  hotkeys:
    - Control+grave                #Ctrl + `
    - Control+Shift+grave
  save_options:
    - full_shape
    - simplification
    - extended_charset

menu:
  page_size: 5

punctuator:
  full_shape:
    ' ' : { commit: '　' }
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : [ 、, ＼ ]
    '|' : [ ・, ｜, '§', '¦' ]
    '`' : ｀
    '~' : [ 〜, ～, 〰 ]
    '!' : { commit: ！ }
    '@' : [ ＠, ☯ ]
    '#' : [ ＃, ⌘ ]
    '%' : [ ％, '°', '℃' ]
    '$' : [ ￥, '$', '€', '£', '¥', '¢', '¤' ]
    '^' : { commit: …… }
    '&' : ＆
    '*' : [ ＊, ・, ·, ×, ※, ❂ ]
    '(' : （
    ')' : ）
    '-' : －
    '_' : ——
    '+' : ＋
    '=' : ＝
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕, ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]
  half_shape:
    ',' : { commit: ， }
    '.' : { commit: 。 }
    '<' : [ 《, 〈, «, ‹ ]
    '>' : [ 》, 〉, », › ]
    '/' : [ 、, '/', ／, ÷ ]
    '?' : { commit: ？ }
    ';' : { commit: ； }
    ':' : { commit: ： }
    '''' : { pair: [ '‘', '’' ] }
    '"' : { pair: [ '“', '”' ] }
    '\' : [ 、, '\', ＼ ]
    '|' : [ ・, '|', ｜, '§', '¦' ]
    '`' : '`'
    '~' : [ '~', 〜, ～, 〰 ]
    '!' : { commit: ！ }
    '@' : '@'
    '#' : '#'
    '%' : [ '%', ％, '°', '℃' ]
    '$' : [ ￥, '$', '€', '£', '¥', '¢', '¤' ]
    '^' : { commit: …… }
    '&' : '&'
    '*' : [ '*', ＊, ・, ·, ×, ※, ❂ ]
    '(' : （
    ')' : ）
    '-' : '-'
    '_' : ——
    '+' : '+'
    '=' : '='
    '[' : [ 「, 【, 〔, ［ ]
    ']' : [ 」, 】, 〕,  ］ ]
    '{' : [ 『, 〖, ｛ ]
    '}' : [ 』, 〗, ｝ ]

key_binder:
  bindings:
    - { when: has_menu, accept: comma, send: comma }      # ㄝ
    - { when: has_menu, accept: period, send: period }    # ㄡ
    - { when: has_menu, accept: minus, send: minus }      # ㄦ
    - { when: has_menu, accept: Left, send: Up }
    - { when: has_menu, accept: Right, send: Down }
    - { when: composing, accept: BackSpace, send: Shift+BackSpace }

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: false
  switch_key:
    Caps_Lock: commit_code
